#!/usr/bin/env python3
"""Convert PNG images into SSD1306-native 1-bit C arrays.

Each output frame is 128x64, packed in SSD1306 GDDRAM page format:
1024 bytes = 8 pages x 128 columns, one byte per column per page, with
bit 0 = the top pixel of that page. That matches the DisplayService
framebuffer exactly, so drawing a full frame is a memcpy.

A monochrome ASCII preview is printed for each frame so you can eyeball
the 1-bit result before it ever reaches hardware.

Usage:
  gallus_image_gen.py --out frames.hpp --namespace gallus::assets \\
      logo=assets/splash/gg-logo.png splash=assets/splash/splash.png
"""

import argparse
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required: tools/.venv/bin/pip install Pillow")

WIDTH = 128
HEIGHT = 64
THRESHOLD = 128


def convert(path: str) -> list:
    """Return 1024 bytes in SSD1306 page format for the image at path."""
    img = Image.open(path).convert("RGBA")

    # Flatten transparency onto black, then greyscale.
    background = Image.new("RGBA", img.size, (0, 0, 0, 255))
    flat = Image.alpha_composite(background, img).convert("L")

    # Fit within 128x64 preserving aspect ratio, centered on black.
    flat.thumbnail((WIDTH, HEIGHT), Image.LANCZOS)
    canvas = Image.new("L", (WIDTH, HEIGHT), 0)
    canvas.paste(flat, ((WIDTH - flat.width) // 2,
                        (HEIGHT - flat.height) // 2))

    mono = canvas.point(lambda p: 255 if p >= THRESHOLD else 0, mode="1")
    pixels = mono.load()

    buf = [0] * (WIDTH * HEIGHT // 8)
    for page in range(HEIGHT // 8):
        for x in range(WIDTH):
            byte = 0
            for bit in range(8):
                if pixels[x, page * 8 + bit]:
                    byte |= (1 << bit)
            buf[page * WIDTH + x] = byte
    return buf


def preview(buf: list) -> str:
    lines = []
    for y in range(HEIGHT):
        page = y // 8
        bit = y % 8
        row = "".join(
            "#" if buf[page * WIDTH + x] & (1 << bit) else " "
            for x in range(WIDTH)
        )
        lines.append(row)
    # Halve vertically so the preview keeps roughly square pixels.
    return "\n".join(lines[::2])


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", required=True)
    parser.add_argument("--namespace", default="gallus::assets")
    parser.add_argument("--no-preview", action="store_true")
    parser.add_argument("frames", nargs="+",
                        help="name=path.png entries")
    args = parser.parse_args()

    frames = {}
    for entry in args.frames:
        if "=" not in entry:
            sys.exit(f"bad frame spec '{entry}', expected name=path.png")
        name, path = entry.split("=", 1)
        frames[name] = convert(path)
        if not args.no_preview:
            print(f"--- {name} ({path}) ---")
            print(preview(frames[name]))
            print()

    ns_open = "".join(f"namespace {p} {{\n"
                      for p in args.namespace.split("::"))
    ns_close = "".join(f"}}  // namespace {p}\n"
                       for p in reversed(args.namespace.split("::")))

    lines = [
        "// Generated by tools/gallus_image_gen.py — DO NOT EDIT.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        ns_open.rstrip("\n"),
        "",
        f"inline constexpr size_t kFrameWidth = {WIDTH};",
        f"inline constexpr size_t kFrameHeight = {HEIGHT};",
        f"inline constexpr size_t kFrameBytes = {WIDTH * HEIGHT // 8};",
        "",
    ]
    for name, buf in frames.items():
        body = ", ".join(f"0x{b:02x}" for b in buf)
        lines.append(f"inline constexpr uint8_t k{name.capitalize()}[] = {{")
        # wrap at 16 bytes per source line
        cells = [f"0x{b:02x}" for b in buf]
        for i in range(0, len(cells), 16):
            lines.append("    " + ", ".join(cells[i:i + 16]) + ",")
        lines.append("};")
        lines.append("")

    lines.append(ns_close.rstrip("\n"))
    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
    print(f"wrote {args.out} ({len(frames)} frame(s))")


if __name__ == "__main__":
    main()
