#!/usr/bin/env python3
"""GallusOS module manifest validator and code generator.

Reads a module's manifest.json, validates it against the module
manifest schema, and emits the C++ registration code that plugs the
module into the ModuleRegistry at static-init time.

Invoked at CMake configure time by the gallus_module() macro
(tools/gallus_module.cmake). Never run at firmware runtime.
"""

import argparse
import json
import re
import sys

VALID_CATEGORIES = {
    "System", "Utilities", "Diagnostics", "Networking", "Bluetooth",
    "WiFi", "RF", "LoRa", "NRF24", "CC1101", "GPS", "GPIO", "Display",
    "Storage", "Developer", "Examples",
}

KNOWN_SERVICES = {
    "events", "scheduler", "logging", "config", "storage", "gpio",
    "wifi", "network", "time", "rest", "display", "battery", "ota", "i2c",
    "ble",
}

REQUIRED_FIELDS = {
    "name": str,
    "version": str,
    "description": str,
    "author": str,
    "license": str,
    "category": str,
}

OPTIONAL_FIELDS = {
    "menu_icon": str,
    "required_services": list,
    "required_gpio": list,
    "events_published": list,
    "events_consumed": list,
    "capabilities": list,
    "config_schema": dict,
}

NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")
VERSION_RE = re.compile(r"^\d+\.\d+\.\d+$")

# Runtime buffers assume this bound: ModuleEventPayload.name and the
# module lifecycle REST route parser both use char[24].
MAX_NAME_LEN = 23


def fail(message: str) -> None:
    print(f"manifest error: {message}", file=sys.stderr)
    sys.exit(1)


def validate(manifest: dict, component_name: str) -> None:
    for field, ftype in REQUIRED_FIELDS.items():
        if field not in manifest:
            fail(f"missing required field '{field}'")
        if not isinstance(manifest[field], ftype):
            fail(f"field '{field}' must be a {ftype.__name__}")

    for field, ftype in OPTIONAL_FIELDS.items():
        if field in manifest and not isinstance(manifest[field], ftype):
            fail(f"field '{field}' must be a {ftype.__name__}")

    unknown = set(manifest) - set(REQUIRED_FIELDS) - set(OPTIONAL_FIELDS)
    if unknown:
        fail(f"unknown field(s): {', '.join(sorted(unknown))}")

    name = manifest["name"]
    if not NAME_RE.match(name):
        fail(f"name '{name}' must be lower_snake_case")
    if len(name) > MAX_NAME_LEN:
        fail(f"name '{name}' is {len(name)} chars — max {MAX_NAME_LEN} "
             "(runtime event payloads and REST routes use char[24])")
    if name != component_name:
        fail(f"name '{name}' must match its directory '{component_name}'")
    if not VERSION_RE.match(manifest["version"]):
        fail(f"version '{manifest['version']}' must be semver (x.y.z)")
    if manifest["category"] not in VALID_CATEGORIES:
        fail(f"category '{manifest['category']}' not one of: "
             f"{', '.join(sorted(VALID_CATEGORIES))}")

    for service in manifest.get("required_services", []):
        if not isinstance(service, str) or service not in KNOWN_SERVICES:
            fail(f"unknown required service '{service}' (known: "
                 f"{', '.join(sorted(KNOWN_SERVICES))})")

    for pin in manifest.get("required_gpio", []):
        if not isinstance(pin, int) or pin < 0 or pin > 48:
            fail(f"required_gpio entry '{pin}' must be a GPIO number")

    for field in ("events_published", "events_consumed", "capabilities"):
        for item in manifest.get(field, []):
            if not isinstance(item, str):
                fail(f"entries of '{field}' must be strings")


def cpp_str(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def emit_string_array(lines: list, symbol: str, values: list) -> str:
    """Emit a constexpr string array; return the initializer reference."""
    if not values:
        return "nullptr"
    items = ", ".join(cpp_str(v) for v in values)
    lines.append(f"constexpr const char* {symbol}[] = {{{items}}};")
    return symbol


def generate(manifest: dict) -> str:
    name = manifest["name"]
    lines = [
        "// Generated by tools/gallus_manifest_gen.py from "
        f"modules/{name}/manifest.json — DO NOT EDIT.",
        "",
        '#include "gallus/sdk/module.hpp"',
        '#include "gallus/sdk/module_registry.hpp"',
        "",
        f"gallus::sdk::Module* gallus_create_{name}();",
        "",
        "namespace {",
        "",
    ]

    services = manifest.get("required_services", [])
    gpio = manifest.get("required_gpio", [])
    published = manifest.get("events_published", [])
    consumed = manifest.get("events_consumed", [])

    services_ref = emit_string_array(lines, "kRequiredServices", services)
    published_ref = emit_string_array(lines, "kEventsPublished", published)
    consumed_ref = emit_string_array(lines, "kEventsConsumed", consumed)

    if gpio:
        items = ", ".join(str(p) for p in gpio)
        lines.append(f"constexpr int kRequiredGpio[] = {{{items}}};")
        gpio_ref = "kRequiredGpio"
    else:
        gpio_ref = "nullptr"

    lines += [
        "",
        "constexpr gallus::sdk::ModuleInfo kInfo = {",
        f"    .name = {cpp_str(name)},",
        f"    .version = {cpp_str(manifest['version'])},",
        f"    .description = {cpp_str(manifest['description'])},",
        f"    .author = {cpp_str(manifest['author'])},",
        f"    .license = {cpp_str(manifest['license'])},",
        f"    .category = {cpp_str(manifest['category'])},",
        f"    .menu_icon = {cpp_str(manifest.get('menu_icon', ''))},",
        f"    .required_services = {services_ref},",
        f"    .required_service_count = {len(services)},",
        f"    .required_gpio = {gpio_ref},",
        f"    .required_gpio_count = {len(gpio)},",
        f"    .events_published = {published_ref},",
        f"    .events_published_count = {len(published)},",
        f"    .events_consumed = {consumed_ref},",
        f"    .events_consumed_count = {len(consumed)},",
        "};",
        "",
        "const gallus::sdk::ModuleRegistrar kRegistrar(",
        f"    kInfo, &gallus_create_{name});",
        "",
        "}  // namespace",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", required=True)
    parser.add_argument("--component", required=True,
                        help="component (directory) name for cross-check")
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    try:
        with open(args.manifest, encoding="utf-8") as handle:
            manifest = json.load(handle)
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"cannot read {args.manifest}: {exc}")

    if not isinstance(manifest, dict):
        fail("manifest root must be a JSON object")

    validate(manifest, args.component)

    with open(args.output, "w", encoding="utf-8") as handle:
        handle.write(generate(manifest))


if __name__ == "__main__":
    main()
